version = 0.1

[default.deploy.parameters]
stack_name = "fondos-first"
resolve_s3 = true
s3_prefix = "fondos-first"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
profile = "aws-alisson-correo-outlook"
